var reward = {
    "success":true,
    "data":{
        "rewards":[
            {
                "rewardId":"14635564",
                "activeId":"14635563",
                "rewardName":"第一格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479632682165_3736.jpg",
                "color":"",
                "rewardSum":"10",
                "rewardSlogan":"第一格",
                "probability":"1.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:06:59 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635566",
                "activeId":"14635563",
                "rewardName":"第二格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479632682165_1835.jpg",
                "color":"",
                "rewardSum":"20",
                "rewardSlogan":"第二格",
                "probability":"2.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635567",
                "activeId":"14635563",
                "rewardName":"第三格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479632915962_8853.jpg",
                "color":"",
                "rewardSum":"30",
                "rewardSlogan":"第三格",
                "probability":"3.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635568",
                "activeId":"14635563",
                "rewardName":"第四格",
                "rewardImg":"./WeDay_files/reward_04.jpg",
                "color":"",
                "rewardSum":"40",
                "rewardSlogan":"第四格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479632968214_6967.jpg",
                "probability":"4.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635569",
                "activeId":"14635563",
                "rewardName":"第五格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479633014859_2922.jpg",
                "color":"",
                "rewardSum":"50",
                "rewardSlogan":"第五格",
                "probability":"5.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635570",
                "activeId":"14635563",
                "rewardName":"第六格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479633052251_971.jpg",
                "color":"",
                "rewardSum":"60",
                "rewardSlogan":"第六格",
                "probability":"6.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635571",
                "activeId":"14635563",
                "rewardName":"第七格",
                "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479633052528_7448.jpg",
                "color":"",
                "rewardSum":"70",
                "rewardSlogan":"第七格",
                "probability":"7.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            },
            {
                "rewardId":"14635572",
                "activeId":"14635563",
                "rewardName":"第八格",
                 "rewardImg":"http://resource.handsight.cn/TVHelp01/img/upload/1479633052249_2202.jpg",
                "color":"",
                "rewardSum":"80",
                "rewardSlogan":"第八格",
                "probability":"8.0",
                "rewardRecord":null,
                "createTime":"Nov 15, 2016 2:13:53 PM",
                "updateTime":"Nov 15, 2016 2:13:53 PM",
                "status":null,
                "drawResults":null,
                "isDel":"1"
            }
        ],
    }

}